### ISSUE TITLE
Android 9 (API 28): android.os.ServiceSpecificException:  (code 7) gets logged

### ISSUE THREAD

**Issue by mreichelt** [googlesamples/android-BasicAndroidKeyStore#3]
When running the sample code on an emulator running Android 9.0 Pie (API 28) and clicking on 'create' and 'sign', the app will log an exception - though it will continue to run fine.

The exception:
```
09-07 14:35:37.535 16583-16583/com.example.android.basicandroidkeystore W/KeyStore: KeyStore exception
    android.os.ServiceSpecificException:  (code 7)
        at android.os.Parcel.createException(Parcel.java:1956)
        at android.os.Parcel.readException(Parcel.java:1910)
        at android.os.Parcel.readException(Parcel.java:1860)
        at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
        at android.security.KeyStore.get(KeyStore.java:195)
        at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificateChain(AndroidKeyStoreSpi.java:118)
        at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:484)
        at java.security.KeyStore.getEntry(KeyStore.java:1560)
        at com.example.android.basicandroidkeystore.BasicAndroidKeyStoreFragment.signData(BasicAndroidKeyStoreFragment.java:234)
        at com.example.android.basicandroidkeystore.BasicAndroidKeyStoreFragment.onOptionsItemSelected(BasicAndroidKeyStoreFragment.java:102)
        at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2394)
        at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3326)
        at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:344)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:386)
        at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1237)
        at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:776)
        at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:148)
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:923)
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:913)
        at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:617)
        at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:147)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

The culprit seems to be this code (also exists in `verifyData` method):
https://github.com/googlesamples/android-BasicAndroidKeyStore/blob/5070deacbd8f85cb7a49aad022cadf4f8a15d22e/Application/src/main/java/com/example/android/basicandroidkeystore/BasicAndroidKeyStoreFragment.java#L233-L234

**Comment by ber4444** [comment]
This is still happening on Android Q, beta 2.
Related bugs:
- https://issuetracker.google.com/issues/113559499
- https://issuetracker.google.com/issues/77664363

**Comment by anthonymonori** [comment]
This issue has been fixed in Beta 4/final SDK release of Android 10: https://issuetracker.google.com/issues/74355119

Can be closed IMHO

**Comment by ber4444** [comment]
It's still an issue on the latest Android 10 update, but nice to see the fix is scheduled to come in "a future version".

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
